// ── Occupation slugs ───────────────────────────────────────────────────────────
// Ordered array used for tab strip display order
export const OCCUPATIONS = [
  { slug: 'physical-therapists',          name: 'Physical Therapists',          short: 'PT' },
  { slug: 'occupational-therapists',      name: 'Occupational Therapists',      short: 'OT' },
  { slug: 'radiation-therapists',         name: 'Radiation Therapists',         short: 'RT' },
  { slug: 'speech-language-pathologists', name: 'Speech-Language Pathologists', short: 'SLP' },
];

// Slug → full DB occupation name (O(1) lookup in server components)
export const SLUGS = Object.fromEntries(OCCUPATIONS.map(o => [o.slug, o.name]));

// ── State abbreviations ────────────────────────────────────────────────────────
// DB stores full state name only; this resolves to 2-letter code for map rendering.
export const STATE_ABBREVS = {
  Alabama:                'AL',
  Alaska:                 'AK',
  Arizona:                'AZ',
  Arkansas:               'AR',
  California:             'CA',
  Colorado:               'CO',
  Connecticut:            'CT',
  Delaware:               'DE',
  'District of Columbia': 'DC',
  Florida:                'FL',
  Georgia:                'GA',
  Hawaii:                 'HI',
  Idaho:                  'ID',
  Illinois:               'IL',
  Indiana:                'IN',
  Iowa:                   'IA',
  Kansas:                 'KS',
  Kentucky:               'KY',
  Louisiana:              'LA',
  Maine:                  'ME',
  Maryland:               'MD',
  Massachusetts:          'MA',
  Michigan:               'MI',
  Minnesota:              'MN',
  Mississippi:            'MS',
  Missouri:               'MO',
  Montana:                'MT',
  Nebraska:               'NE',
  Nevada:                 'NV',
  'New Hampshire':        'NH',
  'New Jersey':           'NJ',
  'New Mexico':           'NM',
  'New York':             'NY',
  'North Carolina':       'NC',
  'North Dakota':         'ND',
  Ohio:                   'OH',
  Oklahoma:               'OK',
  Oregon:                 'OR',
  Pennsylvania:           'PA',
  'Puerto Rico':          'PR',
  'Rhode Island':         'RI',
  'South Carolina':       'SC',
  'South Dakota':         'SD',
  Tennessee:              'TN',
  Texas:                  'TX',
  Utah:                   'UT',
  Vermont:                'VT',
  Virginia:               'VA',
  Washington:             'WA',
  'West Virginia':        'WV',
  Wisconsin:              'WI',
  Wyoming:                'WY',
};
